---
title: "Stats 102B Homework 1"
author: "Christian Jordan"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r message = FALSE, warning = FALSE}
library(pracma)
```

# (1) Angle Between Two Vectors

## (a)
```{r}
get_angle = function(x, y) {
  # Calculates the (counterclockwise) angle between two 2-dimensional vectors
  # Args:
  # x: A single 2-dimensional vector
  # y: A single 2-dimensional vector
  # Return:
  # The counterclockwise angle between x and y
  
  rads <- acos(dot(x,y) / (Norm(x) * Norm(y)))
                      
  rads * (180/pi)
}
```

## (b)
```{r}
get_angle(c(1,0), c(cos(17 * (pi/180)),sin(17 * (pi/180))))
get_angle(c(1,0), c(cos(110 * (pi/180)),sin(110 * (pi/180))))
get_angle(c(1,0), c(cos(270 * (pi/180)),sin(270 * (pi/180))))
```

# (2) Matrix Inverse Properties

## Given that $A^{-1}$ and $B^{-1}$ exist:

## (a) Show that $(A^T)^{-1}=(A^{-1})^T$

$$AA^{-1}=I$$
$$(AA^{-1})^T=I^T$$
$$A^T(A^{-1})^T=I$$
$$(A^T)^{-1}A^T(A^{-1})^T=(A^T)^{-1}I$$
$$(A^{-1})^T=(A^T)^{-1}$$

## (b) Show that $(AB)^{-1}=B^{-1}A^{-1}$



# Eigenvalues

# Ellipses

# Orthogonal Projection

# Modelling
